export const CREATE_DEALHOT_REQUEST = "CREATE_DEALHOT_REQUEST";
export const CREATE_DEALHOT_SUCCESS = "CREATE_DEALHOT_SUCCESS";
export const CREATE_DEALHOT_FAILURE = "CREATE_DEALHOT_FAILURE";

export const GET_ALL_DEALHOT_REQUEST = "GET_ALL_DEALHOT_REQUEST";
export const GET_ALL_DEALHOT_SUCCESS = "GET_ALL_DEALHOT_SUCCESS";
export const GET_ALL_DEALHOT_FAILURE = "GET_ALL_DEALHOT_FAILURE";

export const DELETE_DEALHOT_REQUEST = "DELETE_DEALHOT_REQUEST";
export const DELETE_DEALHOT_SUCCESS = "DELETE_DEALHOT_SUCCESS";
export const DELETE_DEALHOT_FAILURE = "DELETE_DEALHOT_FAILURE";

export const GET_All_DATA_REQUEST = "GET_All_DATA_REQUEST";
export const GET_All_DATA_SUCCESS = "GET_All_DATA_SUCCESS";
export const GET_All_DATA_FAILURE = "GET_All_DATA_FAILURE";







