export const ADD_ITEMS_TO_CART_REQUEST = "ADD_ITEMS_TO_CART_REQUEST"
export const ADD_ITEMS_TO_CART_SUCCESS = "ADD_ITEMS_TO_CART_SUCCESS"
export const ADD_ITEMS_TO_CART_FAILURE = "ADD_ITEMS_TO_CART_FAILURE"

export const GET_CART_REQUEST= "GET_CART_REQUEST"
export const GET_CART_SUCCESS= "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"


export const REMOVE_CART_ITEM_REQUEST= "REMOVE_CART_ITEM_REQUEST"
export const REMOVE_CART_ITEM_SUCCESS= "REMOVE_CART_ITEM_SUCCESS"
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE"


export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE"


export const FIND_CART_ITEMS_REQUEST = 'FIND_CART_ITEMS_REQUEST';
export const FIND_CART_ITEMS_SUCCESS = 'FIND_CART_ITEMS_SUCCESS';
export const FIND_CART_ITEMS_FAILURE = 'FIND_CART_ITEMS_FAILURE';

export const UPDATE_TOTAL_PRICE_CART_REQUEST = 'UPDATE_TOTAL_PRICE_CART_REQUEST';
export const UPDATE_TOTAL_PRICE_CART_SUCCESS = 'UPDATE_TOTAL_PRICE_CART_SUCCESS';
export const UPDATE_TOTAL_PRICE_CART_FAILURE = 'UPDATE_TOTAL_PRICE_CART_FAILURE';

export const SENT_CART_ITEM_REQUEST = "SENT_CART_ITEM_REQUEST";
export const SENT_CART_ITEM_SUCCESS = "SENT_CART_ITEM_SUCCESS";
export const SENT_CART_ITEM_FAILURE = "SENT_CART_ITEM_FAILURE";


export const GET_ALL_CHECKOUT_REQUEST = "GET_CHECKOUT_REQUEST";
export const GET_ALL_CHECKOUT_SUCCESS = "GET_CHECKOUT_SUCCESS";
export const GET_ALL_CHECKOUT_FAILURE = "GET_CHECKOUT_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAILURE = "GET_ALL_ORDER_FAILURE";

export const GET_ALL_ORDER_ITEM_REQUEST = "GET_ALL_ORDER_ITEM_REQUEST";
export const GET_ALL_ORDER_ITEM_SUCCESS = "GET_ALL_ORDER_ITEM_SUCCESS";
export const GET_ALL_ORDER_ITEM_FAILURE = "GET_ALL_ORDER_ITEM_FAILURE";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";








