export const FIND_PRODUCT_BY_ID_REQUEST='FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS= 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'

export const FIND_PRODUCTS_REQUEST="FIND_PRODUCTS_REQUEST"
export const FIND_PRODUCTS_SUCCESS= "FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_FAILURE = "FIND_PRODUCTS_FAILURE"

export const FIND_ALL_PRODUCTS_REQUEST="FIND_PRODUCTS_REQUEST"
export const FIND_ALL_PRODUCTS_SUCCESS="FIND_PRODUCTS_SUCCESS"
export const FIND_ALL_PRODUCTS_FAILURE = "FIND_PRODUCTS_FAILURE"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "DELETE_BRAND_FAILURE";

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const FIND_ALL_BRANDS_REQUEST="FIND_ALL_BRANDS_REQUEST"
export const FIND_ALL_BRANDS_SUCCESS = "FIND_ALL_BRANDS_SUCCESS"
export const FIND_ALL_BRANDS_FAILURE = "FIND_ALL_BRANDS_FAILURE"

export const CREATE_BRAND_REQUEST="CREATE_BRAND_REQUEST"
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS"
export const CREATE_BRAND_FAILURE = "CREATE_BRAND_FAILURE"

export const SEARCH_PRODUCTS_REQUEST="SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_FAILURE = "SEARCH_PRODUCTS_FAILURE"

export const SEARCH_PRODUCTS_SOLD_AT_REQUEST="SEARCH_PRODUCTS_SOLD_AT_REQUEST"
export const SEARCH_PRODUCTS_SOLD_AT_SUCCESS = "SEARCH_PRODUCTS_SOLD_AT_SUCCESS"
export const SEARCH_PRODUCTS_SOLD_AT_FAILURE="SEARCH_PRODUCTS_SOLD_AT_FAILURE"

export const ADD_PRODUCT_TO_FAVOURITE_REQUEST="ADD_PRODUCT_TO_FAVOURITE_REQUEST"
export const ADD_PRODUCT_TO_FAVOURITE_SUCCESS = "ADD_PRODUCT_TO_FAVOURITE_SUCCESS"
export const ADD_PRODUCT_TO_FAVOURITE_FAILURE = "ADD_PRODUCT_TO_FAVOURITE_FAILURE"

export const FIND_ALL_PRODUCT_FAVOURITE_REQUEST="FIND_ALL_PRODUCT_FAVOURITE_REQUEST"
export const FIND_ALL_PRODUCT_FAVOURITE_SUCCESS = "FIND_ALL_PRODUCT_FAVOURITE_SUCCESS"
export const FIND_ALL_PRODUCT_FAVOURITE_FAILURE="FIND_ALL_PRODUCT_FAVOURITE_FAILURE"

export const REMOVE_FAVOURITE_REQUEST="REMOVE_FAVOURITE_REQUEST"
export const REMOVE_FAVOURITE_SUCCESS ="REMOVE_FAVOURITE_SUCCESS"
export const REMOVE_FAVOURITE_FAILURE = "REMOVE_FAVOURITE_FAILURE"


export const FIND_PRODUCTS_BY_BRANDS_REQUEST="FIND_PRODUCTS_BY_BRANDS_REQUEST"
export const FIND_PRODUCTS_BY_BRANDS_SUCCESS = "FIND_PRODUCTS_BY_BRANDS_SUCCESS"
export const FIND_PRODUCTS_BY_BRANDS_FAILURE = "FIND_PRODUCTS_BY_BRANDS_FAILURE"



