export const FIND_PRODUCT_BY_ID_REQUEST='FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS= 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'



export const FIND_ALL_PRODUCTS_REQUEST="FIND_PRODUCTS_REQUEST"
export const FIND_ALL_PRODUCTS_SUCCESS="FIND_PRODUCTS_SUCCESS"
export const FIND_ALL_PRODUCTS_FAILURE = "FIND_PRODUCTS_FAILURE"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "DELETE_BRAND_FAILURE";

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const FIND_ALL_BRANDS_REQUEST="FIND_ALL_BRANDS_REQUEST"
export const FIND_ALL_BRANDS_SUCCESS = "FIND_ALL_BRANDS_SUCCESS"
export const FIND_ALL_BRANDS_FAILURE = "FIND_ALL_BRANDS_FAILURE"

export const CREATE_BRAND_REQUEST="CREATE_BRAND_REQUEST"
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS"
export const CREATE_BRAND_FAILURE = "CREATE_BRAND_FAILURE"

export const SEARCH_PRODUCTS_REQUEST="SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_FAILURE = "SEARCH_PRODUCTS_FAILURE"

export const SEARCH_PRODUCTS_SOLD_AT_REQUEST="SEARCH_PRODUCTS_SOLD_AT_REQUEST"
export const SEARCH_PRODUCTS_SOLD_AT_SUCCESS = "SEARCH_PRODUCTS_SOLD_AT_SUCCESS"
export const SEARCH_PRODUCTS_SOLD_AT_FAILURE="SEARCH_PRODUCTS_SOLD_AT_FAILURE"

export const ADD_PRODUCT_TO_FAVOURITE_REQUEST="ADD_PRODUCT_TO_FAVOURITE_REQUEST"
export const ADD_PRODUCT_TO_FAVOURITE_SUCCESS = "ADD_PRODUCT_TO_FAVOURITE_SUCCESS"
export const ADD_PRODUCT_TO_FAVOURITE_FAILURE = "ADD_PRODUCT_TO_FAVOURITE_FAILURE"

export const ADD_PRODUCT_TO_DEALHOT_REQUEST="ADD_PRODUCT_TO_DEALHOT_REQUEST"
export const ADD_PRODUCT_TO_DEALHOT_SUCCESS = "ADD_PRODUCT_TO_DEALHOT_SUCCESS"
export const ADD_PRODUCT_TO_DEALHOT_FAILURE = "ADD_PRODUCT_TO_DEALHOT_FAILURE"

export const REMOVE_PRODUCT_TO_DEALHOT_REQUEST="REMOVE_PRODUCT_TO_DEALHOT_REQUEST"
export const REMOVE_PRODUCT_TO_DEALHOT_SUCCESS = "REMOVE_PRODUCT_TO_DEALHOT_SUCCESS"
export const REMOVE_PRODUCT_TO_DEALHOT_FAILURE = "REMOVE_PRODUCT_TO_DEALHOT_FAILURE"

export const GET_PRODUCTS_BY_DEALHOT_REQUEST = "GET_PRODUCTS_BY_DEALHOT_REQUEST";
export const GET_PRODUCTS_BY_DEALHOT_SUCCESS = "GET_PRODUCTS_BY_DEALHOT_SUCCESS";
export const GET_PRODUCTS_BY_DEALHOT_FAILURE = "GET_PRODUCTS_BY_DEALHOT_FAILURE";

export const FIND_ALL_PRODUCT_FAVOURITE_REQUEST="FIND_ALL_PRODUCT_FAVOURITE_REQUEST"
export const FIND_ALL_PRODUCT_FAVOURITE_SUCCESS = "FIND_ALL_PRODUCT_FAVOURITE_SUCCESS"
export const FIND_ALL_PRODUCT_FAVOURITE_FAILURE="FIND_ALL_PRODUCT_FAVOURITE_FAILURE"

export const REMOVE_FAVOURITE_REQUEST="REMOVE_FAVOURITE_REQUEST"
export const REMOVE_FAVOURITE_SUCCESS ="REMOVE_FAVOURITE_SUCCESS"
export const REMOVE_FAVOURITE_FAILURE = "REMOVE_FAVOURITE_FAILURE"


export const FIND_PRODUCTS_BY_BRANDS_REQUEST="FIND_PRODUCTS_BY_BRANDS_REQUEST"
export const FIND_PRODUCTS_BY_BRANDS_SUCCESS = "FIND_PRODUCTS_BY_BRANDS_SUCCESS"
export const FIND_PRODUCTS_BY_BRANDS_FAILURE = "FIND_PRODUCTS_BY_BRANDS_FAILURE"

export const FIND_PRODUCTS_BY_BRAND_ID_REQUEST="FIND_PRODUCTS_BY_BRAND_ID_REQUEST"
export const FIND_PRODUCTS_BY_BRAND_ID_SUCCESS = "FIND_PRODUCTS_BY_BRAND_ID_SUCCESS"
export const FIND_PRODUCTS_BY_BRAND_ID_FAILURE = "FIND_PRODUCTS_BY_BRAND-ID_FAILURE"

export const FIND_PRODUCTS_REQUEST="FIND_PRODUCTS_REQUEST"
export const FIND_PRODUCTS_SUCCESS= "FIND_PRODUCTS_SUCCESS"
export const FIND_PRODUCTS_FAILURE = "FIND_PRODUCTS_FAILURE"

export const FIND_PRODUCTS1_REQUEST="FIND_PRODUCTS1_REQUEST"
export const FIND_PRODUCTS1_SUCCESS= "FIND_PRODUCTS1_SUCCESS"
export const FIND_PRODUCTS1_FAILURE = "FIND_PRODUCTS1_FAILURE"

export const FIND_PRODUCTS2_REQUEST="FIND_PRODUCTS2_REQUEST"
export const FIND_PRODUCTS2_SUCCESS= "FIND_PRODUCTS2_SUCCESS"
export const FIND_PRODUCTS2_FAILURE = "FIND_PRODUCTS2_FAILURE"

export const FIND_PRODUCTS3_REQUEST="FIND_PRODUCTS3_REQUEST"
export const FIND_PRODUCTS3_SUCCESS= "FIND_PRODUCTS3_SUCCESS"
export const FIND_PRODUCTS3_FAILURE = "FIND_PRODUCTS3_FAILURE"

export const FIND_PRODUCTS4_REQUEST="FIND_PRODUCTS4_REQUEST"
export const FIND_PRODUCTS4_SUCCESS= "FIND_PRODUCTS4_SUCCESS"
export const FIND_PRODUCTS4_FAILURE = "FIND_PRODUCTS4_FAILURE"

export const FIND_PRODUCTS5_REQUEST="FIND_PRODUCTS5_REQUEST"
export const FIND_PRODUCTS5_SUCCESS= "FIND_PRODUCTS5_SUCCESS"
export const FIND_PRODUCTS5_FAILURE = "FIND_PRODUCTS5_FAILURE"

export const FIND_PRODUCTS6_REQUEST="FIND_PRODUCTS6_REQUEST"
export const FIND_PRODUCTS6_SUCCESS= "FIND_PRODUCTS6_SUCCESS"
export const FIND_PRODUCTS6_FAILURE = "FIND_PRODUCTS6_FAILURE"

export const FIND_PRODUCTS7_REQUEST="FIND_PRODUCTS7_REQUEST"
export const FIND_PRODUCTS7_SUCCESS= "FIND_PRODUCTS7_SUCCESS"
export const FIND_PRODUCTS7_FAILURE = "FIND_PRODUCTS7_FAILURE"

export const FIND_PRODUCTS8_REQUEST="FIND_PRODUCTS8_REQUEST"
export const FIND_PRODUCTS8_SUCCESS= "FIND_PRODUCTS8_SUCCESS"
export const FIND_PRODUCTS8_FAILURE = "FIND_PRODUCTS8_FAILURE"

export const FIND_PRODUCTS9_REQUEST="FIND_PRODUCTS9_REQUEST"
export const FIND_PRODUCTS9_SUCCESS= "FIND_PRODUCTS9_SUCCESS"
export const FIND_PRODUCTS9_FAILURE = "FIND_PRODUCTS9_FAILURE"

export const FIND_PRODUCTS10_REQUEST="FIND_PRODUCTS10_REQUEST"
export const FIND_PRODUCTS10_SUCCESS= "FIND_PRODUCTS10_SUCCESS"
export const FIND_PRODUCTS10_FAILURE = "FIND_PRODUCTS10_FAILURE"